"""
AI Agent REST API Layer.
Provides an interface for external microservices to interact with the LangGraph orchestration engine.
"""

from fastapi import FastAPI
from pydantic import BaseModel, Field
from main import GRAPH

# Initialize the FastAPI application independently of the Chainlit UI
# This separation ensures that the OpenAPI schema generation is not corrupted
# by UI-specific middleware or authentication cookie handlers.
app = FastAPI(
    title="Agentic AI Evaluation API",
    description="RESTful interface for cross-platform technology stack evaluation and semantic reasoning.",
    version="1.0.0",
)


class ChatRequest(BaseModel):
    """
    Schema for the incoming prediction requests.

    Attributes:
        query (str): The natural language prompt or technical question for the agent.
    """

    query: str = Field(
        ...,
        example="How to implement a secure JWT authentication in FastAPI?",
        description="The user input to be processed by the agentic workflow.",
    )


@app.post("/predict")
async def predict(request: ChatRequest):
    """
    Primary inference endpoint for the AI Agent.

    Processes the request through the pre-compiled LangGraph instance.
    Returns the final response generated by the multi-agent orchestration.

    Args:
        request (ChatRequest): The validated request body.

    Returns:
        dict: A dictionary containing the 'answer' from the agent.
    """

    # Construct the initial state for the LangGraph
    # Consistent with the StateGraph schema defined in the core logic
    initial_state = {"messages": [{"role": "user", "content": request.query}]}

    # Asynchronous invocation of the graph to ensure non-blocking operation
    result = await GRAPH.ainvoke(initial_state)

    # Extract the final AI message content from the state history
    # The last message in the list represents the agent's finalized output
    final_answer = result["messages"][-1].content

    return {
        "answer": final_answer,
        "metadata": {"status": "success", "engine": "LangGraph-Core"},
    }


# --- [SWAGGER ACCESS INFO] ---
# Once the server is running (e.g., via uvicorn api:app --port 8001),
# you can access the interactive documentation at:
# http://localhost:8001/docs
